const action_types = Object.freeze({
    // DARK MODE
    SET_DARK_MODE: 'SET_DARK_MODE',

    // BRAND
    BRAND_START: 'BRAND_START',
    BRAND_FAIDED: 'BRAND_FAIDED',
    BRAND_SUCCESS: 'BRAND_SUCCESS',

    GET_LIST_BRAND_SUCCESS: 'GET_LIST_BRAND_SUCCESS',
    GET_BRAND_SUCCESS: 'GET_BRAND_SUCCESS',
    CREATE_BRAND_SUCCESS: 'CREATE_BRAND_SUCCESS',
    DELETE_LIST_BRAND_SUCCESS: 'DELETE_LIST_BRAND_SUCCESS',
    EDIT_BRAND_SUCCESS: 'EDIT_BRAND_SUCCESS',
    EDIT_LIST_BRAND_SUCCESS: 'EDIT_LIST_BRAND_SUCCESS',
    ON_CHANGE_BRAND: 'ON_CHANGE_BRAND',
    SET_DATA_BRAND: 'SET_DATA_BRAND',

    // CHARGE_OF
    CHARGE_OF_START: 'CHARGE_OF_START',
    CHARGE_OF_FAIDED: 'CHARGE_OF_FAIDED',
    CHARGE_OF_SUCCESS: 'CHARGE_OF_SUCCESS',

    GET_LIST_CHARGE_OF_SUCCESS: 'GET_LIST_CHARGE_OF_SUCCESS',
    GET_CHARGE_OF_SUCCESS: 'GET_CHARGE_OF_SUCCESS',
    CREATE_CHARGE_OF_SUCCESS: 'CREATE_CHARGE_OF_SUCCESS',
    DELETE_LIST_CHARGE_OF_SUCCESS: 'DELETE_LIST_CHARGE_OF_SUCCESS',
    EDIT_CHARGE_OF_SUCCESS: 'EDIT_CHARGE_OF_SUCCESS',
    EDIT_LIST_CHARGE_OF_SUCCESS: 'EDIT_LIST_CHARGE_OF_SUCCESS',
    ON_CHANGE_CHARGE_OF: 'ON_CHANGE_CHARGE_OF',
    SET_DATA_CHARGE_OF: 'SET_DATA_CHARGE_OF',

    // DEVICE
    DEVICE_START: 'DEVICE_START',
    DEVICE_FAIDED: 'DEVICE_FAIDED',
    DEVICE_SUCCESS: 'DEVICE_SUCCESS',

    GET_LIST_DEVICE_SUCCESS: 'GET_LIST_DEVICE_SUCCESS',
    GET_DEVICE_SUCCESS: 'GET_DEVICE_SUCCESS',
    CREATE_DEVICE_SUCCESS: 'CREATE_DEVICE_SUCCESS',
    DELETE_LIST_DEVICE_SUCCESS: 'DELETE_LIST_DEVICE_SUCCESS',
    EDIT_DEVICE_SUCCESS: 'EDIT_DEVICE_SUCCESS',
    EDIT_LIST_DEVICE_SUCCESS: 'EDIT_LIST_DEVICE_SUCCESS',
    ON_CHANGE_DEVICE: 'ON_CHANGE_DEVICE',
    SET_DATA_DEVICE: 'SET_DATA_DEVICE',

    // MAKEUP_HAIR
    MAKEUP_HAIR_START: 'MAKEUP_HAIR_START',
    MAKEUP_HAIR_FAIDED: 'MAKEUP_HAIR_FAIDED',
    MAKEUP_HAIR_SUCCESS: 'MAKEUP_HAIR_SUCCESS',

    GET_LIST_MAKEUP_HAIR_SUCCESS: 'GET_LIST_MAKEUP_HAIR_SUCCESS',
    GET_MAKEUP_HAIR_SUCCESS: 'GET_MAKEUP_HAIR_SUCCESS',
    CREATE_MAKEUP_HAIR_SUCCESS: 'CREATE_MAKEUP_HAIR_SUCCESS',
    DELETE_LIST_MAKEUP_HAIR_SUCCESS: 'DELETE_LIST_MAKEUP_HAIR_SUCCESS',
    EDIT_MAKEUP_HAIR_SUCCESS: 'EDIT_MAKEUP_HAIR_SUCCESS',
    EDIT_LIST_MAKEUP_HAIR_SUCCESS: 'EDIT_LIST_MAKEUP_HAIR_SUCCESS',
    ON_CHANGE_MAKEUP_HAIR: 'ON_CHANGE_MAKEUP_HAIR',
    SET_DATA_MAKEUP_HAIR: 'SET_DATA_MAKEUP_HAIR',

    // ROLE
    ROLE_START: 'ROLE_START',
    ROLE_FAIDED: 'ROLE_FAIDED',
    ROLE_SUCCESS: 'ROLE_SUCCESS',

    GET_LIST_ROLE_SUCCESS: 'GET_LIST_ROLE_SUCCESS',
    GET_ROLE_SUCCESS: 'GET_ROLE_SUCCESS',
    CREATE_ROLE_SUCCESS: 'CREATE_ROLE_SUCCESS',
    DELETE_LIST_ROLE_SUCCESS: 'DELETE_LIST_ROLE_SUCCESS',
    EDIT_ROLE_SUCCESS: 'EDIT_ROLE_SUCCESS',
    EDIT_LIST_ROLE_SUCCESS: 'EDIT_LIST_ROLE_SUCCESS',
    ON_CHANGE_ROLE: 'ON_CHANGE_ROLE',
    SET_DATA_ROLE: 'SET_DATA_ROLE',

    // SCHEDULE
    SCHEDULE_START: 'SCHEDULE_START',
    SCHEDULE_FAIDED: 'SCHEDULE_FAIDED',
    SCHEDULE_SUCCESS: 'SCHEDULE_SUCCESS',

    GET_LIST_SCHEDULE_SUCCESS: 'GET_LIST_SCHEDULE_SUCCESS',
    GET_LIST_SCHEDULE_DATE_SUCCESS: 'GET_LIST_SCHEDULE_DATE_SUCCESS',
    GET_SCHEDULE_SUCCESS: 'GET_SCHEDULE_SUCCESS',
    CREATE_SCHEDULE_SUCCESS: 'CREATE_SCHEDULE_SUCCESS',
    DELETE_LIST_SCHEDULE_SUCCESS: 'DELETE_LIST_SCHEDULE_SUCCESS',
    EDIT_SCHEDULE_SUCCESS: 'EDIT_SCHEDULE_SUCCESS',
    EDIT_LIST_SCHEDULE_SUCCESS: 'EDIT_LIST_SCHEDULE_SUCCESS',
    ON_CHANGE_SCHEDULE: 'ON_CHANGE_SCHEDULE',
    SET_DATA_SCHEDULE: 'SET_DATA_SCHEDULE',

    // STYLIST
    STYLIST_START: 'STYLIST_START',
    STYLIST_FAIDED: 'STYLIST_FAIDED',
    STYLIST_SUCCESS: 'STYLIST_SUCCESS',

    GET_LIST_STYLIST_SUCCESS: 'GET_LIST_STYLIST_SUCCESS',
    GET_STYLIST_SUCCESS: 'GET_STYLIST_SUCCESS',
    CREATE_STYLIST_SUCCESS: 'CREATE_STYLIST_SUCCESS',
    DELETE_LIST_STYLIST_SUCCESS: 'DELETE_LIST_STYLIST_SUCCESS',
    EDIT_STYLIST_SUCCESS: 'EDIT_STYLIST_SUCCESS',
    EDIT_LIST_STYLIST_SUCCESS: 'EDIT_LIST_STYLIST_SUCCESS',
    ON_CHANGE_STYLIST: 'ON_CHANGE_STYLIST',
    SET_DATA_STYLIST: 'SET_DATA_STYLIST',

    // TIME_LOCATION
    TIME_LOCATION_START: 'TIME_LOCATION_START',
    TIME_LOCATION_FAIDED: 'TIME_LOCATION_FAIDED',
    TIME_LOCATION_SUCCESS: 'TIME_LOCATION_SUCCESS',

    GET_LIST_TIME_LOCATION_SUCCESS: 'GET_LIST_TIME_LOCATION_SUCCESS',
    GET_TIME_LOCATION_SUCCESS: 'GET_TIME_LOCATION_SUCCESS',
    CREATE_TIME_LOCATION_SUCCESS: 'CREATE_TIME_LOCATION_SUCCESS',
    DELETE_LIST_TIME_LOCATION_SUCCESS: 'DELETE_LIST_TIME_LOCATION_SUCCESS',
    EDIT_TIME_LOCATION_SUCCESS: 'EDIT_TIME_LOCATION_SUCCESS',
    EDIT_LIST_TIME_LOCATION_SUCCESS: 'EDIT_LIST_TIME_LOCATION_SUCCESS',
    ON_CHANGE_TIME_LOCATION: 'ON_CHANGE_TIME_LOCATION',
    SET_DATA_TIME_LOCATION: 'SET_DATA_TIME_LOCATION',

    // USER
    USER_START: 'USER_START',
    USER_FAIDED: 'USER_FAIDED',
    USER_SUCCESS: 'USER_SUCCESS',

    GET_LIST_USER_SUCCESS: 'GET_LIST_USER_SUCCESS',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    DELETE_LIST_USER_SUCCESS: 'DELETE_LIST_USER_SUCCESS',
    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_LIST_USER_SUCCESS: 'EDIT_LIST_USER_SUCCESS',
    ON_CHANGE_USER: 'ON_CHANGE_USER',
    SET_DATA_USER: 'SET_DATA_USER',
})

export default action_types;